name: CI Build
on: workflow_dispatch

env:
  GODOT_VERSION: 4.5
  EXPORT_NAME: polaris-touch
  PROJECT_PATH: .
  SECRET_RELEASE_KEYSTORE_BASE64: ${{ secrets.SECRET_RELEASE_KEYSTORE_BASE64 }}
  SECRET_RELEASE_KEYSTORE_USER: ${{ secrets.SECRET_RELEASE_KEYSTORE_USER }}
  SECRET_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.SECRET_RELEASE_KEYSTORE_PASSWORD }}

jobs:
  export-ios-unsigned:
    name: iOS Export
    runs-on: macos-15
    steps:
      - name: Setup Godot
        run: |
          brew install --cask godot-mono
          mkdir "~/Library/Application Support/Godot/export_templates/4.5.stable.mono"
          wget https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_mono_export_templates.tpz
          unzip Godot_v4.5-stable_mono_export_templates.tpz -d "~/Library/Application Support/Godot/export_templates/4.5.stable.mono"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Import Assets
        run: |
          cd $PROJECT_PATH
          godot --headless --verbose --editor --quit

      - name: iOS Export
        run: |
          mkdir -v -p build/ios
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "iOS" $EXPORT_DIR/ios

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: build/ios

  export-android:
    name: Android Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:mono-4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono

      - name: Import Assets
        run: |
          cd $PROJECT_PATH
          godot --headless --verbose --editor --quit

      - name: Android Build
        run: |
          echo $SECRET_RELEASE_KEYSTORE_BASE64 | base64 --decode > $PROJECT_PATH/release.keystore
          mkdir -v -p build/android
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          sed 's@keystore/release=".*"@keystore/release="'$PROJECT_PATH/release.keystore'"@g' -i export_presets.cfg
          sed 's@keystore/release_user=".*"@keystore/release_user="'$SECRET_RELEASE_KEYSTORE_USER'"@g' -i export_presets.cfg
          sed 's@keystore/release_password=".*"@keystore/release_password="'$SECRET_RELEASE_KEYSTORE_PASSWORD'"@g' -i export_presets.cfg
          godot --headless --verbose --export-release "Android" $EXPORT_DIR/android/$EXPORT_NAME.apk

      - name: Show MSBuild log
        run: |
          cat ~/.local/share/godot/mono/build_logs/*/msbuild_log.txt
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: build/android
